# Generated by Django 5.0.4 on 2024-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('embarazado', models.BooleanField(default=True)),
                ('rut', models.IntegerField(default=0)),
            ],
        ),
    ]
