# Generated by Django 5.0.4 on 2024-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosmodel',
            name='contexto',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datosmodel',
            name='descripcion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datosmodel',
            name='diasperdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datosmodel',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datosmodel',
            name='procedimiento_aplicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datosmodel',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='datosmodel',
            name='sindical',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datosmodel',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
