# Generated by Django 5.0.4 on 2024-05-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_datosmodel_contexto_datosmodel_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10, null=True)),
                ('contexto', models.CharField(max_length=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procedimiento_aplicado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('embarazo', models.BooleanField(default=True)),
                ('sindical', models.BooleanField(default=True)),
                ('edad', models.IntegerField(default=0)),
                ('dias_perdidos', models.IntegerField(default=0)),
                ('accidentes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.accidente')),
            ],
        ),
        migrations.DeleteModel(
            name='DatosModel',
        ),
    ]
