# Generated by Django 5.0.4 on 2024-05-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_persona_dias_perdidos_accidente_dias_perdidos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accidente',
            new_name='Accidente_por_persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='accidentes',
            new_name='Accidentes',
        ),
    ]
