# Generated by Django 5.0.4 on 2024-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_accidente_por_persona_accidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidente',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
